FROM alpine:latest
RUN apk update \
    && apk add --no-cache \
    bash \
    curl \
    jq \
    socat

WORKDIR /

COPY service/mms_inc.sh /
COPY service/mms_main_config.sh /
COPY service/mms_service_config.sh /
COPY horizon/config.json /

CMD /mms_main_config.sh
