FROM alpine:latest
RUN apk update \
    && apk add --no-cache \
    bash \
    curl \
    jq \
    socat

WORKDIR /

COPY service/mms_main.sh /
COPY service/mms_service.sh /
COPY horizon/config.json /

CMD /mms_main.sh
