services:
  http:
    image: ${HTTP_IMAGE}
    ports:
      - "${HTTP_PORT}:5000"
    environment:
      HZN_ORGANIZATION: my_org
      HZN_EXCHANGE_URL: URL
      APP_VIEW_COLUMNS: 1
      APP_MMS_OBJECT_SERVICE_NAME_CONFIG: ng.edge.example.visual.mmsconfig
      APP_APIKEY_USERNAME: iamapikey
      APP_APIKEY_PASSWORD: "-"
      EVENTSTREAMS_BROKER_URLS: "-"
      EVENTSTREAMS_API_KEY: "-"
      EVENTSTREAMS_VISUAL_ML_TOPIC: "-"

    secrets:
      - apikey_ro
  
  infer-tflite:
    image: ${INFER_TFLITE_IMAGE}
    environment:
      APP_MODEL_FMWK: tflite
      APP_MODEL_DIR: /model/tflite
      APP_MI_MODEL: /${TFLITE_MODEL}
      APP_CAMERAS: all
      APP_VIDEO_FILES: /video/sample/${FILE_INPUT}
      APP_RTSPS: ${RTSP_INPUT}
      APP_VIEW_COLUMNS: ${VIEW_COLUMNS}
      DEVICE_ID: ${DEVICE_ID}
      DEVICE_NAME: ${DEVICE_NAME}
      DEVICE_IP_ADDRESS: ${HOST_IP_ADDRESS}
      SHOW_OVERLAY: "true"
      PUBLISH_KAFKA: "false"
      PUBLISH_STREAM: "true"
      DETECT_FACE: "true"
      BLUR_FACE: "false"
      MIN_CONFIDENCE_THRESHOLD: 0.6
      HTTP_PUBLISH_KAFKA_URL: http://${HOST_IP_ADDRESS}:5000/publish/kafka
      HTTP_PUBLISH_STREAM_URL: http://${HOST_IP_ADDRESS}:${HTTP_PORT}/publish/stream
    volumes:
      - type: bind
        source: /home/user/model/tflite
        target: /model/tflite
      - type: bind
        source: /home/user/video/sample
        target: /video/sample
    devices:
      - "/dev/video0:/dev/video0"
    secrets:
      - apikey_ro

  infer-pth:
    image: ${INFER_PTH_IMAGE}
    environment:
      APP_MODEL_FMWK: pth_cpu
      APP_MODEL_DIR: /model/pth
      APP_MI_MODEL: /${PTH_MODEL}
      APP_CAMERAS: all
      APP_VIDEO_FILES: /video/sample/${FILE_INPUT}
      APP_RTSPS: ${RTSP_INPUT}
      APP_VIEW_COLUMNS: ${VIEW_COLUMNS}
      DEVICE_ID: ${DEVICE_ID}
      DEVICE_NAME: ${DEVICE_NAME}
      DEVICE_IP_ADDRESS: ${HOST_IP_ADDRESS}
      SHOW_OVERLAY: "true"
      PUBLISH_KAFKA: "false"
      PUBLISH_STREAM: "true"
      DETECT_FACE: "true"
      BLUR_FACE: "false"
      MIN_CONFIDENCE_THRESHOLD: 0.6
      HTTP_PUBLISH_KAFKA_URL: http://${HOST_IP_ADDRESS}:5000/publish/kafka
      HTTP_PUBLISH_STREAM_URL: http://${HOST_IP_ADDRESS}:${HTTP_PORT}/publish/stream
    volumes:
      - type: bind
        source: /home/user/model/pth
        target: /model/pth
      - type: bind
        source: /home/user/video/sample
        target: /video/sample
    devices:
      - "/dev/video0:/dev/video0"
    secrets:
      - apikey_ro

secrets:
  apikey_ro:
    environment: "CR_DOCKER_APIKEY_RO"




    